variables:
  S3_BUCKET_NAME: "website-lnt"

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  image: node:4.2.2
  script:
   - npm install
   - npm run build
  artifacts:
    paths:
      - dist/

deploy to production:
  stage: deploy
  environment: production
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./dist s3://$S3_BUCKET_NAME/ --recursive
  only:
  - master

deploy to pages:
  stage: deploy
  image: alpine:latest
  environment: staging
  script:
  - mkdir -p ./public
  - cp ./dist/* ./public/
  artifacts:
    paths:
    - public
  except:
  - master

